DROP DATABASE IF exists DBDESAFIO_A;

CREATE DATABASE DBDESAFIO_A;

USE DBDESAFIO_A;

CREATE TABLE MEDICO(

	IDMEDICO INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CRM int NOT NULL,
    PRIMARY KEY (IDMEDICO)
);

CREATE TABLE PACIENTE(

IDPACIENTE INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY (IDPACIENTE)
);

create TABLE MEDICO_PACIENTE(
IDMEDICO INT NOT NULL,
IDPACIENTE INT NOT NULL,
PRIMARY KEY (IDMEDICO, IDPACIENTE),
FOREIGN KEY (IDMEDICO) REFERENCES MEDICO(IDMEDICO),
FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE)

);