-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS EXERCICIO18;

-- CRIANDO A BASE DE DADOS 
CREATE DATABASE EXERCICIO18;
	
-- CONECTANDO NA BASE DE DADOS
USE EXERCICIO18;
-- CRIANDO AS TABELAS

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL
    , NOME VARCHAR(100)
    , CPF VARCHAR(11)
    , DDD_RESIDENCIAL CHAR(2)
    , NUMERO_CNH VARCHAR(10)
    , CELULAR VARCHAR(11)
    , DDD_CELULAR CHAR(2)
    , EMAIL VARCHAR(100)
    , TELEFONE_RESIDENCIAL VARCHAR(11)
    , RUA VARCHAR(150)
    , NUMERO VARCHAR(45)
    , COMPLEMENTO VARCHAR(150)
    , CIDADE VARCHAR(100)
    , BAIRRO VARCHAR(100)
    , ESTADO CHAR(2)
    , CEP VARCHAR(8)
    , PRIMARY KEY (IDCLIENTE)
    );
    
CREATE TABLE LOCACAO (
	IDLOCACAO INT NOT NULL
    , IDCLIENTE INT
    , IDVEICULO INT
    , KM_LOCACAO VARCHAR(45)
    , DATA_ENTREGA DATE 
    , HORA_ENTREGA TIME 
    , HORA_LOCACAO TIME 
    , KM_ENTREGA VARCHAR(45)
    , DATA_LOCACAO DATE 
    , PRIMARY KEY (IDLOCACAO)
);

CREATE TABLE OPCIONAL (
	IDOPCIONAL INT NOT NULL
    , DESCRICAO VARCHAR(100)
    , TIPO VARCHAR(100)
    , PRIMARY KEY (IDOPCIONAL)
);

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL
    , MODELO VARCHAR(100)
    , MARCA VARCHAR(100)
    , ANO_FABRICACAO YEAR
    , ANO_MODELO YEAR
    , COMBUSTIVEL VARCHAR(100)
    , PRIMARY KEY (IDARMA)
);
CREATE TABLE OPCIONAL_VEICULO(
	IDOPCIONAL INT NOT NULL,
	IDVEICULO INT NOT NULL,
	PRIMARY KEY (IDOPCIONAL, IDVEICULO)
    , FOREIGN KEY (IDOPCIONAL) REFERENCES OPCIONAL(IDOPCIONAL)
    , FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);
