-- CRIANDO TABELAS 
 CREATE TABLE FILIAL (
ID_FILIAL INT NOT NULL,
IDFILIAL INT,
NOME VARCHAR(100),
TELEFONE VARCHAR(15),
PRIMARY KEY (ID_FILIAL)
);
 CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIO INT NOT NULL,
NOME VARCHAR(100),
DT_DEMISSAO DATE,
PRIMARY KEY (ID_FUNCIONARIO)
);
 CREATE TABLE CLIENTE (
ID_CLIENTE INT NOT NULL,
IDFILIAL INT,
NOME VARCHAR (100),
TELEFONE VARCHAR (15),

PRIMARY KEY (ID_CLIENTE)
);
 CREATE TABLE PROJETO (
ID_PROJETO INT NOT NULL,
IDCLIENTE INT,
TITULO VARCHAR (100),
DESCRICAO VARCHAR (200),
PRIMARY KEY (ID_PROJETEO)
);

CREATE TABLE ALOCAR(
IDPROJETO INT NOT NULL,
IDFUNCIONARIO INT NOT NULL,
PRIMARY KEY (IDPROJETO, IDFUNCIONARIO),
FOREIGN KEY (IDPROJETO) REFERENCES (PROJETO),
FOREIGN KEY (IDFUNCIONARIO) FUNCIONARIO (IDFUNCIONARIO)
);
