/*2) Uma sorveteria possui um sistema de self-service de sorvetes no qual o cliente pode montar seu sorvete com até 4 bolas (sabores). Criar um
programa que simule esse sistema.
1- Adicionar sabor
2- Remover sabor
3- Visualizar sorvete
4- Finalizar pedido
======== MENSAGENS e VALIDAÇÕES ========
Opção 1-> “Sabor adicionado!” OU “Limite de sabores atingido, remova um sabor!”
Opção 2-> “Sabor removido!” OU “Não existem sabores adicionados!”
Opção 3-> “"Camada 1 - Sabor X, Camada 2 - Sabor Y, etc.” OU “Seu sorvete não possui sabores!”
Opção 4-> “Pedido realizado!” OU “Adicione pelo menos um sabor!” */