DROP DATABASE IF exists DBEXERCICIO07;

CREATE DATABASE DBEXERCICIO07;

USE DBEXERCICIO07;

CREATE TABLE DBEXERCICIO07(

IDHOSPEDE INT NOT NULL auto_increment , 
HOSPEDE_NOME VARCHAR(60), 
HOSPEDE_CPF CHAR(14) NOT NULL, 
HOSPEDE_DTNASCIMENTO DATE , 
HOSPEDE_GENERO VARCHAR(60), 
HOSPEDE_DOCUMENTO_NUMERO VARCHAR(20), 
HOSPEDE_DOCUMENTO_ORGAO VARCHAR(60), 
HOSPEDE_DOCUMENTO_TIPO VARCHAR(60), 
HOSPEDE_NACIONALIDADE VARCHAR(60), 
HOSPEDE_TELEFONE VARCHAR(20), 
HOSPEDE_RESIDENCIA_RUA VARCHAR(60), 
HOSPEDE_RESIDENCIA_NUMERO INT , 
HOSPEDE_RESIDENCIA_BAIRRO VARCHAR(60), 
HOSPEDE_RESIDENCIA_CIDADE VARCHAR(60), 
HOSPEDE_RESIDENCIA_ESTADO VARCHAR(60), 
HOSPEDE_RESIDENCIA_CEP CHAR(8), 
HOSPEDE_RESIDENCIA_PAIS VARCHAR(60), 
HOSPEDE_RESIDENCIA_COMPLEMENTO VARCHAR(160), 
HOSPEDE_ACOMPANHANTE INT, 
HOSPEDE_PROFISSAO VARCHAR(60), 
HOSPEDE_MOTIVO VARCHAR(160), 
HOSPEDE_ENTRADA DATE NOT NULL, 
HOSPEDE_SAIDA DATE NOT NULL, 
HOSPEDE_PROCEDENCIA_CIDADE VARCHAR(60), 
HOSPEDE_PROCEDENCIA_ESTADO VARCHAR(60), 
HOSPEDE_PROCEDENCIA_PAIS VARCHAR(60), 
HOSPEDE_DESTINO_CIDADE VARCHAR(60), 
HOSPEDE_DESTINO_ESTADO VARCHAR(60), 
HOSPEDE_DESTINO_PAIS VARCHAR(60), 
HOTEL_FANTASIA VARCHAR(60), 
HOTEL_ENDERECO_RUA VARCHAR(60), 
HOTEL_ENDERECO_NUMERO INT, 
HOTEL_ENDERECO_COMPLEMENTO VARCHAR(160), 
HOTEL_ENDERECO_BAIRRO VARCHAR(60), 
HOTEL_ENDERECO_CIDADE VARCHAR(60), 
HOTEL_ENDERECO_ESTADO VARCHAR(60) , 
HOTEL_ENDERECO_CEP CHAR(8), 
HOTEL_CNPJ CHAR(14), 
HOTEL_TIPO VARCHAR(60), 
HOTEL_CAT VARCHAR(60), 
HOTEL_RAZAO VARCHAR(60), 
HOTEL_REDE VARCHAR(60), 
HOTEL_MTUR VARCHAR(60), 
HOTEL_TELEFONE VARCHAR(20),

PRIMARY KEY (IDHOSPEDE)
);