-- APAGANDO O BANCO DE DADOS CASO EXISTA 
DROP DATABASE IF exists DBEXEMPLO01;

-- CRIANDO O BANCO DE DADOS
create database DBEXEMPLO01;

-- SELECIONAR O BANCO CRIADO
USE DBEXEMPLO01;

-- CRIANDO AS TABELAS
CREATE TABLE PESSOA (

IDPESSOA INT NOT NULL AUTO_INCREMENT,
NOME varchar(160) NOT NULL,
SEXO CHAR(1),
PRIMARY KEY (IDPESSOA)

);


insert INTO PESSOA (SEXO, NOME)
VALUES ('M', 'MATEUS');

SELECT * FROM PESSOA;