DROP DATABASE IF EXISTS BDEXERCICIO014;

CREATE DATABASE BDEXERCICIO014;

USE BDEXERCICIO014;


CREATE TABLE DEPARTAMENTO(
IDDEPARTAMENTO INT NOT NULL,
RAMAL INT NOT NULL,
NOME_RESPONSAVEL VARCHAR(100),
PRIMARY KEY (IDDEPARTAMENTO)
);


CREATE TABLE COMPUTADOR(
IDCOMPUTADOR INT NOT NULL,
IDDEPARTAMENTO INT NOT NULL,
NUMERO_IDENTIFICACAO VARCHAR(60) NOT NULL,
FABRICANTE VARCHAR(60) NOT NULL,
MODELO DATE NOT NULL,
PRIMARY KEY (IDCOMPUTADOR),
FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);
CREATE table ENDERECO_REDE(
IDENDERECO_REDE INT NOT NULL,
IDCOMPUTADOR INT NOT NULL,
ENDERECO VARCHAR (60) NOT NULL,
MASCARA_REDE VARCHAR (60) NOT NULL,
PRIMARY KEY (IDENDERECO_REDE),
FOREIGN KEY (IDCOMPUTADOR) REFERENCES COMPUTADOR(IDCOMPUTADOR)
);