-- apagando banco de dados --

drop database if exists DBEXERCICIO07;

-- CRIANDO A BAS DE DADOS--

CREATE DATABASE DBEXERCICIO07;

-- CRIANDO TABELAS 
USE DBEXERCICIO07;

CREATE TABLE PESSOA_PASSAPORTE (
	IDPESSOA INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    IDPASSAPORTE int NOT NULL,
    NUMERO VARCHAR (45),
    PRIMARY KEY (IDPESSOA, IDPASSAPORTE)
); 