/*Criação de uma página WEB, onde será possível realizar o cadastro de produtos de uma loja (nome, marca e valor), alterar o valor de um
produto, deletar um produto e apresentar a lista dos produtos para os clientes, na página.
Tudo isso deverá ser realizado em uma única página.
Itens obrigatórios:
- Criação de um array de objetos para armazenar os produtos. Deverá ser armazenados dentro do LocalStorage com a chave "produtosLoja".
(3,0)
- Criação da página HTML para apresentar / alterar / cadastrar / deletar os produtos. (2,0)
- Função para listar os produtos. (1,0)
- Função para alterar o valor de um produto, deverá buscar cada produto pelo seu nome. (2,0)
- Função para deletar um produto. (1,0)
- Função para cadastrar um produto. (1,0) */