DROP  DATABASE IF EXISTS DBEXERCICIO09;

CREATE DATABASE DBEXERCICIO09;

USE DBEXERCICIO09;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    PRIMARY KEY (IDALUNO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL,
    NOME VARCHAR(45),
    PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE ALUNO_PRODUTO(
	IDALUNO INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    primary key (IDALUNO, IDPRODUTO),
    foreign key (IDALUNO) references ALUNO(IDALUNO),
    foreign key (IDPRODUTO) references PRODUTO(IDPRODUTO)
);