DROP DATABASE IF EXISTS BDEXERCICIO013;

CREATE DATABASE BDEXERCICIO013;

USE BDEXERCICIO013;



CREATE table USUARIO(
IDUSUARIO INT NOT NULL ,
NOME VARCHAR (60) NOT NULL,
LOGIN VARCHAR (60) NOT NULL,
SENHA VARCHAR (60) NOT NULL,
DATA_CADASTRO DATE not null,
PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO(
IDVIDEO INT NOT NULL,
TITULO VARCHAR(60) NOT NULL,
CATEGORIA VARCHAR(60) NOT NULL,
DATA_PUBLICACAO DATE NOT NULL,
PRIMARY KEY (IDVIDEO)
);

CREATE TABLE USUARIO_VIDEO(
IDUSUARIO INT NOT NULL,
IDVIDEO INT NOT NULL,
PRIMARY KEY (IDUSUARIO, IDVIDEO),
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDVIDEO) REFERENCES VIDEO(IDVIDEO)
);