/*Crie um projeto de banco de dados para armazenar informações
dos alunos.
Você deve armazenar:
• Nome
• Data de nascimento
• Telefone celular com DDD
• Telefone residencial DDD
• Telefone contato com DDD e nome de contato*/
DROP DATABASE IF exists DBEXEMPLO05;

CREATE DATABASE DBEXEMPLO05;

USE DBEXEMPLO05;

CREATE TABLE ALUNO(
IDALUNO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(145) NOT NULL,
DTNASCIMENTO DATE NOT NULL,
TELEFONE_CELULAR INT NOT NULL,
DDD_CELULAR INT NOT NULL,
TELEFONE_RESIDENCIAL INT,
DDD_RESIDENCIAL INT,
TELEFONE_CONTATO INT NOT NULL,
DDD_CONTATO INT NOT NULL,
NOME_CONTATO VARCHAR(160) NOT NULL,
PRIMARY KEY (IDALUNO)
);