/*Coloque o tipo de dado referente a coluna
-literal
-lógico
-real
-inteiro
*/


// Marca do carro:Literal
// Modelodo carro:Literal
// Ano de fabricação: Inteiro
// Ano de modelo: inteiro
// Cor do veículo:literal
// Valor de compra:real
// Valor de venda:real
// Possui opcionais:logico


// Número do pedido:inteiro
// Sabor da pizza:literal
// Tamanho da pizza:real
// Borda recheada:logico
// Valor de venda:real
// Quantidade da compra: inteiro
// Endereço de entrega: literal
// Valor do frete: real


// Nome do remédio:literal
// Valor de compra: real
// Valor de venda: real
// Remédio é controlado: logico
// Descrição: literal
// Restrições de uso: literal
// Quantidade atual: inteiro
// Quantidade mínima: inteiro
// Uso pediátrico: logico