DROP DATABASE IF exists DBEXERCICIO16;

CREATE DATABASE DBEXERCICIO16;

USE DBEXERCICIO16;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   TELEFONE INT NOT NULL,
   PRIMARY KEY (IDFUNCIONARIO)
   
);

CREATE TABLE PROJETO(
	IDPROJETO INT NOT NULL,
   TITULO VARCHAR(100) NOT NULL,
   ASSUNTO VARCHAR(200) NOT NULL,
   PRIMARY KEY (IDPROJETO)
   
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL,
    IDPROJETO INT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   TELEFONE INT NOT NULL,
   PRIMARY KEY (IDCLIENTE, IDPROJETO),
   FOREIGN KEY (IDPROJETO) REFERENCES PROJETO(IDPROJETO)
);

CREATE TABLE FILIAL(
	IDFILIAL INT NOT NULL,
	IDCLIENTE INT NOT NULL,
    IDFUNCIONARIO INT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   TELEFONE INT NOT NULL,
   PRIMARY KEY (IDFILIAL, IDCLIENTE, IDFUNCIONARIO),
   FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
   FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)

);