/*Nesta atividade você deve enviar o script de correção do banco de dados*/
DROP DATABASE IF EXISTS DBDELEGACIA;

CREATE DATABASE DBDELEGACIA;

USE DBDELEGACIA;

CREATE TABLE CRIME (
	IDCRIME INT NOT NULL,
	DESCRICAO VARCHAR(255),
	RUA VARCHAR(100),
	NUMERO INT,
	COMPLEMENTO VARCHAR(255),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(8),
	CIDADE VARCHAR(100),
	ESTADO CHAR(2)
);

CREATE TABLE CRIMINOSO(
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP CHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE,
  TELEFONE VARCHAR(15)
);

CREATE TABLE OCORRENCIA (
	IDOCORRENCIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DT_OCORRENCIA DATE
);

CREATE TABLE ITEM_OCORRENCIA (
	IDITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDOCORRENCIA INT NOT NULL,
	DESCRICAO VARCHAR (100),
	CONSTRAINT FK_ITEM_OCORRENCIA_OCORRENCIA FOREIGN KEY (IDOCORRENCIA) REFERENCES OCORRENCIA(IDOCORRENCIA)
);

CREATE TABLE VITIMA (
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP VARCHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE
);

CREATE TABLE COMETE(
	IDCRIME INT NOT NULL,
	IDCRIMINOSO INT NOT NULL
);

CREATE TABLE ATACA (
	OBSERVACAO CHAR(1)
);

CREATE TABLE SOFRE (
	IDCRIME INT NOT NULL,
	IDVITIMA INT NOT NULL
);

CREATE TABLE ARMA (
	IDARMA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(110)
);

CREATE TABLE USADA (
	IDARMA INT NOT NULL,
	IDCRIME INT NOT NULL
);

alter table CRIME
ADD column DTCRIME DATE NOT NULL, 
ADD primary key (IDCRIME);

ALTER TABLE CRIMINOSO
ADD column NOME VARCHAR(45) NOT NULL,
ADD column IDCRIMINOSO INT NOT NULL primary key;

ALTER TABLE VITIMA
ADD column NOME VARCHAR (45),
ADD column IDVITIMA INT NOT NULL primary KEY;

DROP TABLE ITEM_OCORRENCIA;
drop table OCORRENCIA;

ALTER TABLE COMETE
ADD primary key (IDCRIME, IDCRIMINOSO),
ADD foreign key (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO),
ADD foreign key (IDCRIME) REFERENCES CRIME (IDCRIME);

ALTER TABLE ATACA
ADD column IDVITIMA INT NOT NULL ,
ADD column IDCRIMINOSO INT NOT NULL ,
ADD primary key (IDVITIMA, IDCRIMINOSO),
ADD foreign key (IDVITIMA) REFERENCES VITIMA (IDVITIMA),
ADD foreign key (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO),
DROP column OBSERVACAO;

ALTER TABLE SOFRE
ADD primary key (IDCRIME, IDVITIMA),
ADD foreign key (IDCRIME) REFERENCES CRIME (IDCRIME),
ADD foreign key (IDVITIMA) REFERENCES VITIMA (IDVITIMA);

ALTER table ARMA
ADD column IDENTIFICACAO VARCHAR(45),
CHANGE  MARCA DESCRICAO VARCHAR(110),
ADD column TIPO ENUM ('ARMA FOGO', 'ARMA BRANCA');

ALTER TABLE USADA
ADD primary key (IDARMA, IDCRIME),
ADD foreign key (IDARMA) REFERENCES ARMA (IDARMA),
ADD foreign key (IDCRIME) REFERENCES CRIME (IDCRIME);









