DROP DATABASE IF EXISTS BDEXERCICIO011;

CREATE DATABASE BDEXERCICIO011;

USE BDEXERCICIO011;



CREATE table VEICULO_RESGISTRO(
IDVEICULO INT NOT NULL ,
MODELO VARCHAR (60) NOT NULL,
MARCA VARCHAR (60) not null,
ANO INT NOT NULL,
PLACA VARCHAR(7),
IDREGISTRO INT NOT NULL,
RENAVAN CHAR(11) NOT NULL,
DATA_DIA DATE NOT NULL, 
CIDADE VARCHAR(60) NOT NULL,
ESTADO CHAR(2) NOT NULL,
PRIMARY KEY (IDVEICULO, IDREGISTRO)
);