-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO18;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO18;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO18;

-- CRIANDO AS TABELAS
CREATE TABLE DEPARTAMENTO (
	ID_DEPARTAMENTO INT NOT NULL
    , NOME VARCHAR(45)
    , ID_DEPARTAMENTO_RESPONSAVEL INT
    , PRIMARY KEY (ID_DEPARTAMENTO)
    , FOREIGN KEY (ID_DEPARTAMENTO_RESPONSAVEL) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT NOT NULL 
    , NOME VARCHAR(45)
    , TELEFONE VARCHAR(15)
    , IDDEPARTAMENTO INT
    , PRIMARY KEY (ID_FUNCIONARIO)
    , FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);