drop  database if exists DBEXERCICIO15;

CREATE DATABASE DBEXERCICIO15;

USE DBEXERCICIO15;

CREATE table CRIMINOSO(

IDCRIMINOSO INT NOT NULL,
NOME VARCHAR (100) NOT NULL,
DTNASCIMENTO DATE NOT NULL,
primary key(IDCRIMINOSO)

);
CREATE TABLE CRIME(

	IDCRIME INT NOT NULL,
    DTCRIME DATE NOT NULL,
    DESCRICAO VARCHAR(300),
    PRIMARY KEY (IDCRIME)


);

CREATE TABLE VITIMA(

IDVITIMA INT NOT NULL, 
NOME VARCHAR(100) NOT NULL,
DTNASCIMENTO DATE,
PRIMARY KEY (IDVITIMA)


);

CREATE TABLE COMETER(

	IDCOMETER INT NOT NULL,
    IDCRIME INT NOT NULL,
    IDCRIMINOSO INT NOT NULL,
    PRIMARY KEY (IDCOMETER),
    FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME),
	FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO)

);

CREATE TABLE SOFRER (

	IDSOFRER INT NOT NULL,
    IDVITIMA INT NOT NULL,
    IDCRIME INT NOT NULL,
    PRIMARY KEY (IDSOFRER),
    FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME),
	FOREIGN KEY (IDVITIMA) REFERENCES VITIMA (IDVITIMA)

);

CREATE TABLE ATACAR (

	IDATACAR INT NOT NULL,
    IDVITIMA INT NOT NULL,
    IDCRIMINOSO INT NOT NULL,
    PRIMARY KEY (IDATACAR),
    FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO),
	FOREIGN KEY (IDVITIMA) REFERENCES VITIMA (IDVITIMA)

);
CREATE TABLE ARMA(

IDARMA INT NOT NULL,
IDENTIFICACAO VARCHAR (100) NOT NULL,
TIPO VARCHAR(100)  NOT NULL,
PRIMARY KEY (IDARMA)

);


CREATE TABLE USAR (

	IDUSAR INT NOT NULL,
    IDARMA INT NOT NULL,
    IDCRIME INT NOT NULL,
    PRIMARY KEY (IDUSAR),
    FOREIGN KEY (IDARMA) REFERENCES ARMA (IDARMA),
	FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME)

);